version: '3'

services:
  app:
    image: ${DOCKER_USERNAME}/snap-ticket:${TAG}
    container_name: snap-ticket
    ports:
      - "8080:8080"
    env_file:
      - snap-ticket/.env
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /home/ubuntu/logs:/home/logs  # 로그 파일 저장 디렉토리
    restart: always
    