name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # 데이터베이스 - RDS
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build (no tests)
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/snap-ticket:${{ github.sha }} .
            docker push ${{ secrets.DOCKER_USERNAME }}/snap-ticket:${{ github.sha }}

      - name: Create .env file
        run: | 
          echo "DB_URL=${{ secrets.DB_URL }}" > .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "TAG=${{ github.sha }}" >> .env
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env

      - name: Upload docker-compose.yml, .env to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > snapticketKey.pem
          chmod 600 snapticketKey.pem
          scp -o StrictHostKeyChecking=no -i snapticketKey.pem docker-compose/docker-compose.yml ubuntu@${{ secrets.EC2_HOST }}:~/snap-ticket/docker-compose.yml
          scp -o StrictHostKeyChecking=no -i snapticketKey.pem .env ubuntu@${{ secrets.EC2_HOST }}:~/snap-ticket/.env

      - name: Run docker-compose on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i snapticketKey.pem ubuntu@${{ secrets.EC2_HOST }} <<EOF
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          cd /home/ubuntu/snap-ticket
          docker-compose down || true
          docker-compose pull
          docker-compose up -d
          EOF
          rm snapticketKey.pem
